12.0 fix it bug price
grap/odoo-addons-intercompany-trade pull request #26
Opened 2021-03-08 09:42 UTC by quentinDupont

2021-03-16 23:05 UTC, legalsylvain requested changes
Yop. je sais pas si cette PR est nécessaire. Au final, c'étiat pas un problème de code mais de position fiscale.
en changeant la position fiscale, tout est OK.

![image](https://user-images.githubusercontent.com/3407482/111391189-657f2a00-86b4-11eb-93fc-c389d8e881e7.png)

On clot la PR et on archive le ticket ?

2021-03-30 08:31 UTC, quentinDupont commented
> Yop. je sais pas si cette PR est nécessaire. Au final, c'étiat pas un problème de code mais de position fiscale.
> en changeant la position fiscale, tout est OK.
> 
> ![image](https://user-images.githubusercontent.com/3407482/111391189-657f2a00-86b4-11eb-93fc-c389d8e881e7.png)
> 
> On clot la PR et on archive le ticket ?

Ah bon ? je vois pas le lien entre ton explication et la capture d'écran

2021-03-30 08:34 UTC, legalsylvain commented
yop . quand tu as changé de EDC à EDC transaction inter société, cela n'a pas changé la position fiscale qui restait en mode normal ou B2B (en tout cas, pas "Transaction inter société"). Du coup, le calcul de TVA était daubé. 
je n'ai pas eu besoin d'appliquer ton patch, pour résoudre le soucis, il m'a juste fallu corriger la position fiscale, et j'ai validé et c'était good.

2021-03-30 09:01 UTC, quentinDupont commented
> yop . quand tu as changé de EDC à EDC transaction inter société, cela n'a pas changé la position fiscale qui restait en mode normal ou B2B (en tout cas, pas "Transaction inter société"). Du coup, le calcul de TVA était daubé.
> je n'ai pas eu besoin d'appliquer ton patch, pour résoudre le soucis, il m'a juste fallu corriger la position fiscale, et j'ai validé et c'était good.

aaaah
et beh.. tant de temps pour ça :shrug: merci tu gères :pray:

2021-03-30 09:01 UTC, closed without merging